[package]
name = "service"
version = "0.1.0"
edition = "2024"

[dependencies]
sea-orm = { version = "1.1.11", features = [
  "sqlx-postgres",
  "runtime-tokio-native-tls",
  "macros",
  "mock",
  "debug-print",
] }
entity = { path = "../entity" }

[lints.clippy]
pedantic = "warn"
